Repository icosa-foundation/open-brush, pull requests merged in 2022-12, with the labels that each got.

#337 Use a unique cache for each platform/rendering backend
  .github/workflows/build.yml
Labels: bugfix, maintenance

#335 Set ASTC to default tex format for android
  .github/workflows/build.yml
  ProjectSettings/ProjectSettings.asset
Labels: maintenance

#334 Use custom unity input to fix pressure points
  Assets/InputSystem.inputsettings.asset
  Assets/Scripts/Input/UnityXRInputAction.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: bugfix
