Repository icosa-foundation/open-brush, pull requests merged in 2022-09, with the labels that each got.

#280 Tidyup README, fix oculus builds
  Assets/Plugins/Android/AndroidManifest.xml
  README.md
  TILT_BRUSH_BRAND_GUIDELINES.md
  open-brush.png
Labels: documentation

#279 Feature/large mesh support xr
  Assets/Scripts/Batching/Batch.cs
  Assets/Scripts/Export/ExportUtils.cs
Labels: enhancement

#274 Feature/widgets respect layers
  Assets/Models/PanelBorder_Stretchable.fbx
  Assets/Models/PanelBorder_Stretchable.fbx.meta
  Assets/Prefabs/Panels/LayersPanel.prefab
  Assets/Scripts/Commands/DuplicateSelectionCommand.cs
  Assets/Scripts/Commands/SelectCommand.cs
  Assets/Scripts/GUI/MultistateButton.cs
  Assets/Scripts/Layers/LayerUI_Manager.cs
  Assets/Scripts/Save/MetadataUtils.cs
  Assets/Scripts/Save/SaveLoadScript.cs
  Assets/Scripts/Save/SketchMetadata.cs
  Assets/Scripts/SceneScript.cs
  Assets/Scripts/SelectionManager.cs
  Assets/Scripts/SketchMemoryScript.cs
  Assets/Scripts/Stroke.cs
  Assets/Scripts/Tools/SelectionTool.cs
  Assets/Scripts/Widgets/GrabWidget.cs
  Assets/Scripts/Widgets/ImageWidget.cs
  Assets/Scripts/Widgets/ModelWidget.cs
  Assets/Scripts/Widgets/StencilWidget.cs
  Assets/Scripts/Widgets/VideoWidget.cs
Labels: bugfix

#287 Correct color picker visual from gamma to linear
  Assets/Shaders/ColorPicker.shader
  Assets/Shaders/ColorPicker_hs_l.shader
  Assets/Shaders/ColorPicker_hs_logv.shader
  Assets/Shaders/ColorPicker_sl_h.shader
  Assets/Shaders/ColorPicker_sv_h.shader
  Assets/Shaders/Include/Brush.cginc
  Assets/Shaders/Include/ColorSpaceConvert.cginc
  Assets/Shaders/Include/ColorSpaceConvert.cginc.meta
Labels: bugfix

#294 Fix for Toolkit export regex matching on glb import
  Assets/Scripts/Export/ExportUtils.cs
Labels: bugfix
