Repository icosa-foundation/open-brush, pull requests merged in 2023-06, with the labels that each got.

#446 Backport a simplified version of model import from EditableModels
  Assets/Scripts/API/ApiMethods.EditableModels.cs
  Assets/Scripts/API/ApiMethods.EditableModels.cs.meta
  Assets/Scripts/Commands/CreateWidgetCommand.cs
  Assets/Scripts/Widgets/GrabWidget.cs
Labels: enhancement

#454 (Re-enable) Free disk space before starting the Android build
  .github/workflows/build.yml
Labels: infrastructure

#457 Hotfix/widget layers offby1
  Assets/Scripts/SceneScript.cs
Labels: bugfix

#460 Correctly calculate changelogs commensurate on commencement of correctional commit
  .github/workflows/build.yml
Labels: infrastructure
