Repository icosa-foundation/open-brush, pull requests merged in 2023-08, with the labels that each got.

#488 Fix an NRE when hitting stop in editor
  Assets/Scripts/WebcamSurface.cs
Labels: bugfix

#485 Fix issue where undo didn't respect symmetry mode
  Assets/Scripts/Commands/SymmetryWidgetVisibleCommand.cs
  Assets/Scripts/PointerManager.cs
Labels: bugfix

#487 Fix selection bug after cloning to multimirrors
  Assets/Scripts/Commands/MultimirrorDuplicateCommand.cs
Labels: bugfix

#486 Support per widget setting for two sided and set it to true when duplicating to multimirror
  Assets/Materials/ReferenceImage.mat
  Assets/Scripts/Commands/MultimirrorDuplicateCommand.cs
  Assets/Scripts/Save/MetadataUtils.cs
  Assets/Scripts/Save/SketchMetadata.cs
  Assets/Scripts/Widgets/ImageWidget.cs
  Assets/Scripts/Widgets/Media2dWidget.cs
  Assets/Scripts/Widgets/VideoWidget.cs
  Assets/Shaders/ReferenceImage.shader
Labels: bugfix

#492 Opt-in large mesh support
  Assets/Scripts/Batching/Batch.cs
  Assets/Scripts/Export/ExportCollector.cs
  Assets/Scripts/UserConfig.cs
Labels: enhancement

#494 Thumbstick changes AdvancedSlider value + visual feedback on controller model
  Assets/Materials/ControllerPad_ChangeSliderValue.mat
  Assets/Materials/ControllerPad_ChangeSliderValue.mat.meta
  Assets/Materials/ControllerPad_ChangeSliderValueActive.mat
  Assets/Materials/ControllerPad_ChangeSliderValueActive.mat.meta
  Assets/Prefabs/Panels/Widgets/AdvancedSlider.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/GUI/AdvancedSlider.cs
  Assets/Scripts/GUI/BasePanel.cs
  Assets/Scripts/GUI/BaseSlider.cs
  Assets/Scripts/Input/ControllerGeometry.cs
  Assets/Scripts/Input/ControllerMaterialCatalog.cs
  Assets/Shaders/ChangeSliderValue.shader
  Assets/Shaders/ChangeSliderValue.shader.meta
Labels: enhancement

#495 Custom skybox
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanel.prefab
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanelIconBackgroundImage.prefab
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanelIconBackgroundImage.prefab.meta
  Assets/Resources/DefaultBackgroundImages.meta
  Assets/Resources/DefaultBackgroundImages/ATTRIBUTION.txt.bytes
  Assets/Resources/DefaultBackgroundImages/ATTRIBUTION.txt.bytes.meta
  Assets/Resources/DefaultBackgroundImages/panorama.jpg.bytes
  Assets/Resources/DefaultBackgroundImages/panorama.jpg.bytes.meta
  Assets/Resources/DefaultBackgroundImages/stereopanorama.jpg.bytes
  Assets/Resources/DefaultBackgroundImages/stereopanorama.jpg.bytes.meta
  Assets/Resources/Environments/CustomSkybox.mat
  Assets/Resources/Environments/CustomSkybox.mat.meta
  Assets/Resources/Environments/CustomStereoSkybox.mat
  Assets/Resources/Environments/CustomStereoSkybox.mat.meta
  Assets/Resources/Icons/environment.png.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/App.cs
  Assets/Scripts/BackgroundImageCatalog.cs
  Assets/Scripts/BackgroundImageCatalog.cs.meta
  Assets/Scripts/GUI/LoadBackgroundImageButton.cs
  Assets/Scripts/GUI/LoadBackgroundImageButton.cs.meta
  Assets/Scripts/GUI/ReferenceButton.cs
  Assets/Scripts/ReferenceImage.cs
  Assets/Scripts/ReferenceImageCatalog.cs
  Assets/Scripts/ReferencePanelBackgroundImageTab.cs
  Assets/Scripts/ReferencePanelBackgroundImageTab.cs.meta
  Assets/Scripts/Save/SaveLoadScript.cs
  Assets/Scripts/Save/SketchMetadata.cs
  Assets/Scripts/SceneSettings.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#506 Replace all references to icosa-gallery with icosa-foundation
  .github/FUNDING.yml
  .github/workflows/build.yml
  Assets/Editor/Tests/TestMathUtils.cs
  Assets/Scenes/Main.unity
  CONTRIBUTING.md
  README.md
Labels: infrastructure

#507 Remove old vscode package
  Packages/manifest.json
  Packages/packages-lock.json
Labels: dependencies
