Repository icosa-foundation/open-brush, pull requests merged in 2023-02, with the labels that each got.

#387 Send a "raw" changelog to Oculus for Beta releases
  .github/workflows/build.yml
Labels: enhancement

#396 Release note tweaks
  .github/workflows/build.yml
Labels: infrastructure

#395 Improve cache management in build system
  .github/workflows/build.yml
  .github/workflows/delete_branch_cache.yml
Labels: infrastructure

#397 Improve cache management in build system, part 2
  .github/workflows/delete_branch_cache.yml
Labels: infrastructure

#382 Enable Microsoft motion controller profile (WMR)
  Assets/Prefabs/VrSystems/VrControllers/UnityXR/UnityXRWmrControls.prefab
  Assets/Scripts/Input/UnityXRControllerInfo.cs
  Assets/Scripts/Input/UnityXRFakeThumbTouchComposite.cs
  Assets/Scripts/Input/UnityXRFakeThumbTouchComposite.cs.meta
  Assets/Scripts/Input/UnityXRInput.inputactions
  Assets/Scripts/Input/UnityXRInputAction.cs
  Assets/XR/Settings/Open XR Package Settings.asset
Labels: bugfix

#400 Fix for issue where strokes on deleted layers could still return true…
  Assets/Scripts/Save/SketchWriter.cs
Labels: bugfix

#403 Support hotfixes / maintenance releases properly
  .github/workflows/build.yml
Labels: infrastructure

#410 Change release note formatting
  .github/workflows/build.yml
Labels: infrastructure

#415 Automatically create a changelog in open-brush-docs
  .github/workflows/build.yml
Labels: infrastructure
