Repository icosa-foundation/open-brush, pull requests merged in 2023-01, with the labels that each got.

#365 Update Unity version + packages
  .github/workflows/build.yml
  Assets/Oculus/OculusProjectConfig.asset
  Assets/Scenes/Main.unity
  Assets/XR/Settings/Open XR Package Settings.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TimelineSettings.asset
Labels: maintenance

#367 Fix stereo recording mode on Windows
  Assets/ThirdParty/UnityODS/Materials/Warp2.shader
Labels: bugfix

#369 Re-add monoscopic builds
  .github/workflows/build.yml
  Assets/Editor/BuildTiltBrush.cs
  Assets/Prefabs/VrSystems/VrSystem.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Config.cs
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#371 Remove upload of experimental build(s) and pre-release channel for Steam. Just keep beta channel
  .github/workflows/build.yml
Labels: maintenance

#379 Fix Pimax release; versioned files numbers and directory packaging
  .github/workflows/build.yml
Labels: bugfix

#380 Automatically generate changelog, rather than doing it manually
  .github/workflows/build.yml
Labels: enhancement

#384 Don't show "uncategorized" in the release notes if it's empty
  .github/workflows/build.yml
Labels: bugfix

#381 Upload builds to Viveport automatically
  .github/workflows/build.yml
Labels: enhancement
