Repository icosa-foundation/open-brush, pull requests merged in 2023-12, with the labels that each got.

#575 Fixes for Quest Accounts Panel showing Desktop version
  Assets/Prefabs/PopUps/PopUpWindow_Accounts_Mobile.prefab
  Assets/Scripts/GUI/PanelManager.cs
Labels: bugfix

#577 Fix OAuth sign in on Android
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.57.0.2601/Google.Apis.Drive.v3.1.57.0.2601.nupkg
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.57.0.2601/lib/netstandard2.0/Google.Apis.Drive.v3.dll
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/.signature.p7s
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/Google.Apis.Drive.v3.1.64.0.3155.nupkg
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/Google.Apis.Drive.v3.1.64.0.3155.nupkg.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/LICENSE
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/LICENSE.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0/Google.Apis.Drive.v3.dll
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0/Google.Apis.Drive.v3.dll.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0/Google.Apis.Drive.v3.pdb
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0/Google.Apis.Drive.v3.pdb.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0/Google.Apis.Drive.v3.xml
  Assets/ThirdParty/NuGet/Packages/Google.Apis.Drive.v3.1.64.0.3155/lib/netstandard2.0/Google.Apis.Drive.v3.xml.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.57.0.2637/.signature.p7s
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.57.0.2637/Google.Apis.PeopleService.v1.1.57.0.2637.nupkg
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.57.0.2637/lib/netstandard2.0/Google.Apis.PeopleService.v1.dll
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/.signature.p7s
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/Google.Apis.PeopleService.v1.1.64.0.3093.nupkg
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/Google.Apis.PeopleService.v1.1.64.0.3093.nupkg.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/LICENSE
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/LICENSE.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0/Google.Apis.PeopleService.v1.dll
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0/Google.Apis.PeopleService.v1.dll.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0/Google.Apis.PeopleService.v1.pdb
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0/Google.Apis.PeopleService.v1.pdb.meta
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0/Google.Apis.PeopleService.v1.xml
  Assets/ThirdParty/NuGet/Packages/Google.Apis.PeopleService.v1.1.64.0.3093/lib/netstandard2.0/Google.Apis.PeopleService.v1.xml.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: bugfix

#579 Fix Keijiro Tube and mark Race and Digital as "broken" (hidden by default)
  Assets/Resources/X/Brushes/Digital/Digital.asset
  Assets/Resources/X/Brushes/KeijiroTube/KeijiroTube.shader
  Assets/Resources/X/Brushes/Race/Race.asset
Labels: bugfix

#578 Base Multiplayer implementation
  .github/workflows/build.yml
  .gitignore
  .pre-commit-config.yaml
  Assets/Editor/BuildTiltBrushPostProcess.cs
  Assets/Editor/BuildTiltBrushPostProcess.cs.meta
  Assets/Oculus/OculusProjectConfig.asset
  Assets/OculusMR.meta
  Assets/OculusMR/AnchorToGuide.cs
  Assets/OculusMR/AnchorToGuide.cs.meta
  Assets/OculusMR/OculusMR.prefab
  Assets/OculusMR/OculusMR.prefab.meta
  Assets/OculusMR/OculusMRController.cs
  Assets/OculusMR/OculusMRController.cs.meta
  Assets/OculusMR/SceneAnchorBase.prefab
  Assets/OculusMR/SceneAnchorBase.prefab.meta
  Assets/OculusMR/SpatialAnchorManager.cs
  Assets/OculusMR/SpatialAnchorManager.cs.meta
  Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion
  Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion.meta
  Assets/Plugins/Android/AndroidManifest.xml
  Assets/Prefabs/HMDMesh.prefab
  Assets/Prefabs/HMDMesh.prefab.meta
  Assets/Resources/Multiplayer.meta
  Assets/Resources/Multiplayer/Photon.meta
  Assets/Resources/Multiplayer/Photon/PhotonPlayerRig.prefab
  Assets/Resources/Multiplayer/Photon/PhotonPlayerRig.prefab.meta
  Assets/Resources/OculusRuntimeSettings.asset
  Assets/Scenes/Main.unity
  Assets/Scripts/Commands/BaseCommand.cs
  Assets/Scripts/Commands/BrushStrokeCommand.cs
  Assets/Scripts/Commands/DeleteStrokeCommand.cs
  Assets/Scripts/Config.cs
  Assets/Scripts/Multiplayer.meta
  Assets/Scripts/Multiplayer/MultiplayerDataStructs.cs
  Assets/Scripts/Multiplayer/MultiplayerDataStructs.cs.meta
  Assets/Scripts/Multiplayer/MultiplayerInterfaces.cs
  Assets/Scripts/Multiplayer/MultiplayerInterfaces.cs.meta
  Assets/Scripts/Multiplayer/MultiplayerManager.cs
  Assets/Scripts/Multiplayer/MultiplayerManager.cs.meta
  Assets/Scripts/Multiplayer/Photon.meta
  Assets/Scripts/Multiplayer/Photon/PhotonManager.cs
  Assets/Scripts/Multiplayer/Photon/PhotonManager.cs.meta
  Assets/Scripts/Multiplayer/Photon/PhotonPlayerRig.cs
  Assets/Scripts/Multiplayer/Photon/PhotonPlayerRig.cs.meta
  Assets/Scripts/Multiplayer/Photon/PhotonRPC.cs
  Assets/Scripts/Multiplayer/Photon/PhotonRPC.cs.meta
  Assets/Scripts/Multiplayer/Photon/PhotonStructs.cs
  Assets/Scripts/Multiplayer/Photon/PhotonStructs.cs.meta
  Assets/Scripts/PassthroughManager.cs
  Assets/Scripts/PointerManager.cs
  Assets/Scripts/SecretsConfig.cs
  Assets/Scripts/SketchMemoryScript.cs
  Assets/Scripts/Stroke.cs
  Assets/Scripts/StrokeData.cs
  Assets/Scripts/VrSdk.cs
  Assets/XR/Settings/OpenXR Editor Settings.asset
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#586 Separate Publishing Quest 1 and Quest 2+ into two jobs
  .github/workflows/build.yml
Labels: infrastructure

#582 Fix colours not being calculated when toggling multimirror. Cleanup some dead code
  Assets/Scripts/API/ApiMethods.MultiMirror.cs
  Assets/Scripts/GUI/MirrorOptionsPopUpWindow.cs
  Assets/Scripts/PointerManager.cs
Labels: bugfix

#587 Fixes for Sketchbook and popup
  Assets/Prefabs/Panels/SketchbookPanel.prefab
  Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenu.prefab
  Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenuMobile.prefab
Labels: bugfix

#591 Update LeakyPen.shader
  Assets/Resources/X/Brushes/LeakyPen/LeakyPen.shader
Labels: bugfix

#593 Change build directories to align with the unity-builder standard directories
  .github/workflows/build.yml
  Support/steam/main_depot.vdf.j2
Labels: infrastructure

#592 Catch exceptions in DoBuild() and print them in a way that Github will highlight
  Assets/Editor/BuildTiltBrush.cs
Labels: infrastructure

#594 Automatically create a new cache whenever the dependencies change
  .github/workflows/build.yml
Labels: infrastructure

#595 Only save PackageCache if it's based on the unmodified packages-lock.json
  .github/workflows/build.yml
Labels: infrastructure

#588 Don't include the _BackUpThisFolder_ButDontShipItWithYourGame folder in the artifacts
  .github/workflows/build.yml
Labels: infrastructure

#600 Update artifact actions from v3 to v4
  .github/workflows/build.yml
  .github/workflows/get_license.yml
Labels: dependencies

#601 Correctly set model layer when loading a sketch
  Assets/Scripts/ModelCatalog.cs
  Assets/Scripts/Widgets/ModelWidget.cs
Labels: bugfix

#597 Upload Pico builds automatically
  .github/workflows/build.yml
Labels: infrastructure

#603 Update actions from Pico CI PR to v4
  .github/workflows/build.yml
Labels: infrastructure

#604 Don't include the changelog as notes for Pico (limit 1000 characters)
  .github/workflows/build.yml
Labels: infrastructure

#602 Fix positioning of layer rename keyboard
  Assets/Prefabs/PopUps/PopupWindow_LayerOptions.prefab
Labels: bugfix

#606 Don't allow selection of media widgets if not on the active layer
  Assets/Scripts/SketchControlsScript.cs
Labels: bugfix
