Repository icosa-foundation/open-brush, pull requests merged in 2023-11, with the labels that each got.

#557 Update game-ci build to v4
  .github/workflows/build.yml
  Assets/Editor/BuildTiltBrush.cs
Labels: infrastructure

#559 Only save a cache if it doesn't exist (overwrite doesn't work)
  .github/workflows/build.yml
Labels: infrastructure

#560 Update license used for PRs from forks
  .github/workflows/build.yml
Labels: infrastructure

#566 Enable masking of UNITY_PASSWORD
  .github/workflows/build.yml
Labels: infrastructure

#563 Update Android SDK Target to v32 (Android 12); request MANAGE_EXTERNAL_STORAGE
  Assets/Plugins/Android/AndroidManifest.xml
  Assets/Scenes/Loading.unity
  Assets/Scripts/LoadingScene.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#567 Temp revert controller i18n
  Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesRightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3LeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3RightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixRightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/ViveControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/WmrLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/WmrRightControllerGeometry.prefab
Labels: maintenance

#570 [TEMP] Use a forked version of unity-builder that doesn't randomize UUIDs
  .github/workflows/build.yml
Labels: infrastructure

#569 Quest panel UI fixes
  Assets/Prefabs/Panels/LabsPanel_Mobile.prefab
  Assets/Scenes/Main.unity
Labels: bugfix

#574 Speed up the Disk Cleanup step
  .github/workflows/build.yml
Labels: infrastructure
