Repository icosa-foundation/open-brush, pull requests merged in 2023-07, with the labels that each got.

#406 Feature/xr keyboard
  Assets/Prefabs/Keyboard.meta
  Assets/Prefabs/Keyboard/Key.prefab
  Assets/Prefabs/Keyboard/Key.prefab.meta
  Assets/Prefabs/Keyboard/Keyboard.prefab
  Assets/Prefabs/Keyboard/Keyboard.prefab.meta
  Assets/Prefabs/Keyboard/NumericKeyboard.prefab
  Assets/Prefabs/Keyboard/NumericKeyboard.prefab.meta
  Assets/Prefabs/Panels/SketchbookPanel.prefab
  Assets/Prefabs/Panels/SketchbookPanel_Mobile.prefab
  Assets/Prefabs/PopUps/PopUpWindow_Keyboard.prefab
  Assets/Prefabs/PopUps/PopUpWindow_Keyboard.prefab.meta
  Assets/Prefabs/PopUps/PopUpWindow_NumericKeyboard.prefab
  Assets/Prefabs/PopUps/PopUpWindow_NumericKeyboard.prefab.meta
  Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenu.prefab
  Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenuMobile.prefab
  Assets/Scripts/GUI/KeyboardButton.cs
  Assets/Scripts/GUI/KeyboardButton.cs.meta
  Assets/Scripts/GUI/KeyboardPopUpWindow.cs
  Assets/Scripts/GUI/KeyboardPopUpWindow.cs.meta
  Assets/Scripts/Save/DiskSceneFileInfo.cs
  Assets/Scripts/Save/FileSketchSet.cs
  Assets/Scripts/Save/SceneFileInfo.cs
  Assets/Scripts/Save/SketchSet.cs
  Assets/Scripts/Sharing/GoogleDriveSketchSet.cs
  Assets/Scripts/Sharing/PolySketchSet.cs
  Assets/Scripts/SketchControlsScript.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_de.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
  Assets/Settings/Localization/Strings/Strings_es.asset
  Assets/Settings/Localization/Strings/Strings_fr.asset
  Assets/Settings/Localization/Strings/Strings_ja.asset
  Assets/Settings/Localization/Strings/Strings_ko.asset
  Assets/Settings/Localization/Strings/Strings_zh.asset
  Assets/ThirdParty/UltimateXR Keyboard.meta
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardKeyUI.cs
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardKeyUI.cs.meta
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardToggleSymbolsPage.cs
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardToggleSymbolsPage.cs.meta
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardUI.cs
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardUI.cs.meta
  Assets/ThirdParty/UltimateXR Keyboard/LICENCE
  Assets/ThirdParty/UltimateXR Keyboard/LICENCE.meta
Labels: enhancement

#450 Grab widgets snap to guides where appropriate
  Assets/Scripts/WidgetManager.cs
  Assets/Scripts/Widgets/GrabWidget.cs
  Assets/Scripts/Widgets/SelectionWidget.cs
  Assets/Scripts/Widgets/StencilWidget.cs
Labels: enhancement

#464 Multicam recording fix
  Assets/Prefabs/ControllerHint.prefab
Labels: bugfix

#421 Simple 2D viewing mode when no headset is present
  Assets/Prefabs/NoPeekingCamera.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/App.cs
  Assets/Scripts/GUI/TouchscreenVirtualKey.cs
  Assets/Scripts/GUI/TouchscreenVirtualKey.cs.meta
  Assets/Scripts/GUI/ViewModeUI.cs
  Assets/Scripts/GUI/ViewModeUI.cs.meta
  Assets/Scripts/InitNoHeadsetMode.cs
  Assets/Scripts/InitNoHeadsetMode.cs.meta
  Assets/Scripts/InputManager.cs
  Assets/Scripts/SketchControlsScript.cs
  Assets/Scripts/Tools/FlyTool.cs
Labels: enhancement

#467 Keyboard code improvements and bug fixes
  Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenu.prefab
  Assets/Scripts/GUI/KeyboardPopUpWindow.cs
  Assets/Scripts/GUI/KeyboardPopupButton.cs
  Assets/Scripts/GUI/KeyboardPopupButton.cs.meta
  Assets/Scripts/GUI/MenuPopUpWindow.cs
  Assets/Scripts/GUI/OptionButton.cs
  Assets/Scripts/Save/DiskSceneFileInfo.cs
  Assets/Scripts/Save/FileSketchSet.cs
  Assets/Scripts/Save/SceneFileInfo.cs
  Assets/Scripts/Sharing/GoogleDriveSketchSet.cs
  Assets/Scripts/Sharing/PolySketchSet.cs
  Assets/Scripts/SketchControlsScript.cs
Labels: bugfix

#468 Fix missing localization for a few promo popups
  Assets/Prefabs/Panels/AdminPanel.prefab
  Assets/Scenes/Main.unity
Labels: bugfix

#469 Add Quest support to the pure Android XR build
  Assets/Plugins/Android/AndroidManifest.xml
Labels: enhancement

#470 Update steam deployment to remove superflous parameters
  .github/workflows/build.yml
Labels: infrastructure

#471 Restore Steam password; it seems to be needed
  .github/workflows/build.yml
Labels: maintenance

#472 Update BrushController.cs
  Assets/Scripts/BrushController.cs
Labels: bugfix

#278 Use GLTFast as the primary load; fall back to the old code if it fails
  Assets/Scripts/API/ApiMethods.EditableModels.cs
  Assets/Scripts/GUI/ModelButton.cs
  Assets/Scripts/ImportGltfast.cs
  Assets/Scripts/ImportGltfast.cs.meta
  Assets/Scripts/Model.cs
  Assets/Scripts/ObjModelScript.cs
  Assets/Scripts/Widgets/ModelWidget.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/BurstAotSettings_Android.json
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/PackageManagerSettings.asset
Labels: enhancement

#301 Fix bug with snap rotation on rotated canvas.
  Assets/Scripts/Widgets/GrabWidget.cs
Labels: bugfix

#442 Load HttpListener in a background thread; fixes delay on China mobile hotspots
  Assets/Scripts/Sharing/HttpServer.cs
Labels: bugfix

#478 Update mikepenz/release-changelog-builder-action to v4
  .github/workflows/build.yml
Labels: dependencies

#477 Webcam (or other streaming video source) panel
  Assets/Prefabs/Panels/ExtraPanel.prefab
  Assets/Prefabs/Panels/LabsPanel.prefab
  Assets/Prefabs/Panels/WebcamPanel.prefab
  Assets/Prefabs/Panels/WebcamPanel.prefab.meta
  Assets/Prefabs/Webcam.prefab
  Assets/Prefabs/Webcam.prefab.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/GUI/BasePanel.cs
  Assets/Scripts/WebcamSurface.cs
  Assets/Scripts/WebcamSurface.cs.meta
  ProjectSettings/PackageManagerSettings.asset
Labels: enhancement

#484 Fix webcam breaking Oculus builds
  Assets/Prefabs/Panels/LabsPanel.prefab
  Assets/Scripts/WebcamSurface.cs
Labels: bugfix
