Repository icosa-foundation/open-brush, pull requests merged in 2023-09, with the labels that each got.

#496 Support SVG for reference images
  Assets/Manifest.asset
  Assets/Resources/Brushes/Poly/Pbr/SvgTemplate.asset
  Assets/Resources/Brushes/Poly/Pbr/SvgTemplate.asset.meta
  Assets/Scripts/Export/ExportCollector.cs
  Assets/Scripts/Export/ImportMaterialCollector.cs
  Assets/Scripts/ReferenceImage.cs
  Assets/Scripts/ReferenceImageCatalog.cs
  Assets/ThirdParty/TiltBrushToolkit/Scripts/TbtSettings.cs
  Assets/TiltBrushToolkitSettings.asset
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#520 Separate Rift and Quest upload
  .github/workflows/build.yml
Labels: infrastructure

#523 Temporarily disable Mac CI builds because we don't have room for the cache it creates
  .github/workflows/build.yml
Labels: infrastructure

#522 Add i18n for WMR, Pico 3, 4, Valve Index, and Vive
  Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesRightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3LeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3RightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixRightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/ViveControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/WmrLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/WmrRightControllerGeometry.prefab
Labels: enhancement

#526 Fixes 3D models being omitted from GLTF export since switch to GLTFast
  Assets/Scripts/Export/ImportMaterialCollector.cs
  Assets/Scripts/ImportGltfast.cs
  Assets/Scripts/Model.cs
Labels: bugfix

#508 Move selection to current layer
  Assets/Prefabs/Panels/LayersPanel.prefab
  Assets/Resources/Icons/copy-to-layer.png
  Assets/Resources/Icons/copy-to-layer.png.meta
  Assets/Resources/Icons/move-to-layer.png
  Assets/Resources/Icons/move-to-layer.png.meta
  Assets/Scripts/Commands/SelectCommand.cs
  Assets/Scripts/Layers/LayerUI_Manager.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
Labels: enhancement

#528 JSON exports also include the sketch metadata
  Assets/Scripts/Export/Export.cs
  Assets/Scripts/Save/SketchSnapshot.cs
Labels: enhancement

#529 Don't overwrite user colour unless we're in multimirror mode
  Assets/Scripts/PointerManager.cs
Labels: bugfix

#535 [Pico] Add Chinese build, disable accounts
  .github/workflows/build.yml
  Assets/Editor/BuildTiltBrush.cs
  Assets/Prefabs/PopUps/PopUpWindow_Accounts.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Config.cs
  Assets/Scripts/GUI/ProfilePopUpWindow.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
Labels: enhancement

#533 Fix admin panel promo scale
  Assets/Prefabs/Panels/AdminPanel.prefab
Labels: bugfix

#530 Minimal changes to fix editor on MacOS with Apple Silicon
  Assets/Scripts/SystemAudioMonitor.cs
  Assets/Scripts/VisualizerCSCoreFFT.cs
  Assets/Scripts/VisualizerCSCoreFilter.cs
  Assets/Scripts/VisualizerManager.cs
  Assets/ThirdParty/Sonic Ether/Natural Bloom/Shaders/SENaturalBloomAndDirtyLens.shader
Labels: bugfix

#538 Remove passthrough prefab if not supported
  Assets/Scripts/GUI/LightingPopUpWindow.cs
Labels: bugfix
