Repository icosa-foundation/open-brush, pull requests merged in 2024-09, with the labels that each got.

#761 Fix contextual boundary
  .github/workflows/build.yml
  Assets/Editor/BuildTiltBrushPostProcess.cs
  Assets/Scripts/PassthroughManager.cs
  Assets/Scripts/VrSdk.cs
Labels: bugfix

#762 Disable ENABLE_CONTEXTUAL_BOUNDARYLESS_APP as it's still experimental
  .github/workflows/build.yml
Labels: bugfix

#765 Update some UPM packages
  Packages/manifest.json
  Packages/packages-lock.json
Labels: dependencies

#770 Update Zapbox SDK
  Packages/manifest.json
  Packages/packages-lock.json
Labels: dependencies

#771 gzip config.vdf before storing as a secret
  .github/workflows/build.yml
Labels: infrastructure
