Repository icosa-foundation/open-brush, pull requests merged in 2024-04, with the labels that each got.

#675 Fix automatic changelog page in the docs; update to the new (as of Jan 26th) path
  .github/workflows/build.yml
Labels: infrastructure

#676 Merge the contents of the release-history directory instead of overwriting
  .github/workflows/build.yml
Labels: infrastructure

#682 Minor formatting improvements
  Assets/Editor/Tests/TestExport.cs
  Assets/Editor/ToolkitUtils.cs
  Assets/Scripts/API/ApiManager.cs
  Assets/Scripts/API/ApiMethods.Utils.cs
  Assets/Scripts/Export/Export.cs
  Assets/Scripts/Export/ExportFbx.cs
  Assets/Scripts/Export/FbxUtils.cs
  Assets/Scripts/Export/ImportMaterialCollector.cs
  Assets/Scripts/FbxReader.cs
  Assets/Scripts/GUI/PanelManager.cs
  Assets/Scripts/Model.cs
  Assets/Scripts/OverlayManager.cs
  Assets/Scripts/Util/SerializableGuid.cs
  Assets/Scripts/WidgetManager.cs
Labels: infrastructure

#678 Allow generation of sphere with gesture on mobile
  Assets/Scripts/PointerManager.cs
Labels: enhancement

#683 Release Linux Viewer/Standalone on Steam and Github
  .github/workflows/build.yml
  Support/steam/app.vdf.j2
  Support/steam/installscript_win.vdf.j2
  Support/steam/main_depot.linux.vdf.j2
Labels: infrastructure

#695 De-initialize XR Subsytems properly
  Assets/Scripts/VrSdk.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: bugfix

#697 Fix Advanced Tools panel initial position
  Assets/Prefabs/Panels/AdvancedToolsPanel.prefab
  Assets/Prefabs/Panels/AdvancedToolsPanel_Mobile.prefab
Labels: bugfix

#687 Preview spheres for 360 images
  Assets/Materials/360 Panorama Sphere.mat
  Assets/Materials/360 Panorama Sphere.mat.meta
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanel.prefab
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanelIconBackgroundImage.prefab
  Assets/Scripts/GUI/LoadBackgroundImageButton.cs
  Assets/Scripts/ReferencePanelBackgroundImageTab.cs
  Assets/Shaders/360PanoramaWarp.shader
  Assets/Shaders/360PanoramaWarp.shader.meta
Labels: enhancement
