Repository icosa-foundation/open-brush, pull requests merged in 2024-05, with the labels that each got.

#701 Fix stereo pano sphere preview
  Assets/Shaders/360PanoramaWarp.shader
Labels: bugfix

#702 Damn panel spacing
  Assets/Prefabs/Panels/ExtraPanel.prefab
  Assets/Prefabs/Panels/ExtraPanel_Mobile.prefab
Labels: UX

#706 MacOS: sign all bundles, rather than listing them explicitly
  .github/workflows/build.yml
Labels: infrastructure

#704 Enable file system watcher on mobile
  Assets/PlatformConfigMobile.asset
Labels: bugfix

#707 UnityGltf import is meant to default to off
  Assets/Scripts/UserConfig.cs
Labels: bugfix

#703 Add a section in the changelog for UI/UX PRs
  .github/workflows/build.yml
Labels: infrastructure

#613 Passthrough Hull Brush
  Assets/Manifest_Experimental.asset
  Assets/Resources/X/Brushes/PassthroughHull.meta
  Assets/Resources/X/Brushes/PassthroughHull/HullPrefabPassthrough.prefab
  Assets/Resources/X/Brushes/PassthroughHull/HullPrefabPassthrough.prefab.meta
  Assets/Resources/X/Brushes/PassthroughHull/PassthroughHull.asset
  Assets/Resources/X/Brushes/PassthroughHull/PassthroughHull.asset.meta
  Assets/Resources/X/Brushes/PassthroughHull/PassthroughHull.mat
  Assets/Resources/X/Brushes/PassthroughHull/PassthroughHull.mat.meta
  Assets/Resources/X/Brushes/PassthroughHull/buttonimage.png
  Assets/Resources/X/Brushes/PassthroughHull/buttonimage.png.meta
  Assets/Scripts/BrushCatalog.cs
  Assets/Scripts/VrSdk.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
  Assets/Shaders/Passthrough.shader
  Assets/Shaders/Passthrough.shader.meta
Labels: enhancement

#712 Add support for a [xCI BUILD DEV] (without the x) to build Development builds
  .github/workflows/build.yml
Labels: infrastructure

#713 Fix artifact upload of development builds
  .github/workflows/build.yml
Labels: infrastructure

#715 Fix issue where transparent brushes were invisible in Quest passthrough mode.
  Assets/Scripts/VrSdk.cs
Labels: bugfix

#718 Update the (very rarely used) Unity License Test action
  .github/workflows/test_unity_credentials.yml
Labels: infrastructure

#719 Add Pico support to the generic OpenXR build
  Assets/Plugins/Android/AndroidManifest.xml
Labels: enhancement
