Repository icosa-foundation/open-brush, pull requests merged in 2024-03, with the labels that each got.

#636 Add yamlfmt and enforce via pre-commit
  .github/FUNDING.yml
  .github/workflows/build.yml
  .github/workflows/delete_branch_cache.yml
  .github/workflows/generate_certs.yml
  .github/workflows/get_license.yml
  .github/workflows/ios_setup.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test_unity_credentials.yml
  .pre-commit-config.yaml
  .yamlfmt
Labels: infrastructure

#634 Select the fastlane lane based on whether it's a beta (testflight) or formal (app store)
  .github/workflows/build.yml
Labels: infrastructure

#638 Zapbox: Set to iPhone only for now
  ProjectSettings/ProjectSettings.asset
Labels: bugfix

#639 Add a workflow to export (encrypted) secrets
  .github/workflows/export_secrets.yml
Labels: infrastructure

#642 [Zapbox] Temp set portrait orientation
  Assets/Editor/BuildTiltBrush.cs
  ProjectSettings/ProjectSettings.asset
Labels: bugfix

#645 Correctly set the androidVersionCode on a build rerun
  .github/workflows/build.yml
Labels: bugfix

#650 Fix broken Dependabot PRs
  .github/workflows/build.yml
Labels: infrastructure

#652 Zapbox set up everything else
  Assets/Editor/BuildTiltBrush.cs
  Assets/Manifest_Zapbox.asset
  Assets/Manifest_Zapbox.asset.meta
  Assets/Prefabs/VrSystems/ControllerGeometries/ZapboxLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/ZapboxLeftControllerGeometry.prefab.meta
  Assets/Prefabs/VrSystems/ControllerGeometries/ZapboxRightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/ZapboxRightControllerGeometry.prefab.meta
  Assets/Prefabs/VrSystems/VrControllers/UnityXR/UnityXRZapboxControls.prefab
  Assets/Prefabs/VrSystems/VrControllers/UnityXR/UnityXRZapboxControls.prefab.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/App.cs
  Assets/Scripts/VrSdk.cs
  Assets/Textures/Trademarked/TiltBrushLogoZapbox.png
  Assets/Textures/Trademarked/TiltBrushLogoZapbox.png.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: bugfix

#655 Localization Fixes
  Assets/Scripts/Brushes/BrushDescriptor.cs
  Assets/Scripts/CameraPathCaptureRig.cs
  Assets/Scripts/Environment.cs
  Assets/Scripts/GUI/AdminPanel.cs
  Assets/Scripts/GUI/AudioVizPopUpWindow.cs
  Assets/Scripts/GUI/BasePanel.cs
  Assets/Scripts/GUI/LightsPanel.cs
  Assets/Scripts/GUI/ModelButton.cs
  Assets/Scripts/GUI/OptionButton.cs
  Assets/Scripts/GUI/PolyPanel.cs
  Assets/Scripts/GUI/SketchbookPanel.cs
  Assets/Scripts/GUI/UIComponent.cs
  Assets/Scripts/Layers/LayerUI_Manager.cs
  Assets/Scripts/LoadingScene.cs
  Assets/Scripts/OverlayManager.cs
  Assets/Scripts/ReferencePanelTab.cs
  Assets/Scripts/Sharing/ProfileButton.cs
  Assets/Scripts/TiltMeterScript.cs
  Assets/Scripts/TutorialCard.cs
  Assets/Scripts/Tutorials/HintObjectScript.cs
  Assets/Scripts/Tutorials/PromoManager.cs
  Assets/Settings/Localization/Localization Settings.asset
  Assets/ThirdParty/UltimateXR Keyboard/KeyboardKeyUI.cs
Labels: bugfix

#653 Remove broken custom drawer and fix corrupted value
  Assets/Editor/SerializedPropertyReferenceDrawer.cs
  Assets/Editor/SerializedPropertyReferenceDrawer.cs.meta
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanelTabVideo.prefab
Labels: bugfix

#658 DMG Issues
  .github/workflows/build.yml
Labels: infrastructure

#659 Compliance with Meta Age Group API requirements
  Assets/Scripts/VrSdk.cs
Labels: enhancement

#657 Turn off MSAA for Zapbox
  Assets/AddressableAssetsData/iOS/addressables_content_state.bin
  Assets/Scripts/Rendering/RenderWrapper.cs
Labels: bugfix

#660 Reset default environment. Passthrough only for Zapbox
  Assets/Scenes/Main.unity
  Assets/Scripts/EnvironmentCatalog.cs
Labels: bugfix

#662 Branding Refresh
  Assets/Textures/Trademarked/logo.png
  Assets/Textures/Trademarked/logowatermark.png
  Assets/Textures/Trademarked/logowatermarklabs.png
  Assets/Textures/Trademarked/logowatermarkwhite.png
  README.md
  Support/macos/background.png
  Support/macos/background@2x.png
  open-brush.png
Labels: documentation

#664 Reset default brush to Light
  Assets/Scenes/Main.unity
  Assets/Scripts/BrushCatalog.cs
Labels: bugfix

#665 Don't push iOS Zapbox builds to the Apple Store; just to testflight (even for formal builds)
  .github/workflows/build.yml
Labels: infrastructure

#670 Always specify --age-group for Oculus
  .github/workflows/build.yml
Labels: infrastructure
