Repository icosa-foundation/open-brush, pull requests merged in 2024-06, with the labels that each got.

#722 Fix issue where images that are too large fail to load without any in…
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanelIconBackgroundImage.prefab
  Assets/Prefabs/Panels/ReferencePanel/ReferencePanelTabImage.prefab
  Assets/Scripts/GUI/LoadBackgroundImageButton.cs
  Assets/Scripts/GUI/LoadReferenceImageButton.cs
  Assets/Scripts/ReferenceImage.cs
  Assets/Settings/Localization/Strings/Strings Shared Data.asset
  Assets/Settings/Localization/Strings/Strings_en.asset
Labels: bugfix

#727 Run ovr-platform-util on Linux instead of Mac
  .github/workflows/build.yml
Labels: infrastructure

#708 Unity 2022 LTS
  .github/workflows/build.yml
  Assets/InputSystem.inputsettings.asset
  Assets/Oculus/OculusProjectConfig.asset
  Assets/Prefabs/VrSystems/XRRig.prefab
  Assets/Prefabs/VrSystems/XRRig.prefab.meta
  Assets/Resources/OculusRuntimeSettings.asset
  Assets/Scenes/Loading.unity
  Assets/Scenes/Main.unity
  Assets/Scripts/Input/UnityXRInputAction.cs
  Assets/ThirdParty/UnityODS/TiltBrushStandardSpecular.shader
  Assets/XR/Settings/Oculus Settings.asset
  Assets/XR/Settings/Open XR Package Settings.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/boot.config
  README.md
Labels: maintenance

#732 Fix Q1 upload
  Assets/Plugins/Android/AndroidManifest.xml
Labels: infrastructure

#733 Fix iOS builds after the unity upgrade
  .github/workflows/build.yml
  Gemfile.lock
  fastlane/Fastfile
Labels: infrastructure
