Repository icosa-foundation/open-brush, pull requests merged in 2025-02, with the labels that each got.

#818 Allow the erase tool to also "erase" media widgets
  Assets/Scripts/Tools/EraserTool.cs
Labels: enhancement

#826 Upload Pico to ArborXR
  .github/workflows/build.yml
Labels: infrastructure

#825 Fix editor issues with localization
  Assets/Settings/Localization/Localization Settings.asset
Labels: bugfix

#819 The eraser tool should not erase pinned widgets
  Assets/Scripts/Tools/EraserTool.cs
Labels: bugfix

#787 Switch scoped registries to OpenUPM
  Packages/manifest.json
Labels: infrastructure

#830 Use Xcode 16.2 to build Zapbox
  .github/workflows/build.yml
Labels: infrastructure
