Repository icosa-foundation/open-brush, pull requests merged in 2025-09, with the labels that each got.

#896 PR 893 minor fixes
  Assets/Scripts/Rendering/StillFrameSequenceExporter.cs
  Assets/ThirdParty/Logitech/Scripts/VrStylusHandler.cs
Labels: bugfix

#899 GLTF files on android have no textures
  Assets/Resources/UnityGLTFSettings.asset
  Assets/Scripts/API/Lua/LuaManager.cs
  Assets/Scripts/ImportGltfast.cs
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: bugfix

#908 Fix ArborXR upload again (use the --wait option)
  .github/workflows/build.yml
Labels: infrastructure

#902 Fix builds from forks with just main (no tags)
  .github/workflows/build.yml
Labels: infrastructure

#909 Improve build resiliency
  .github/workflows/build.yml
Labels: infrastructure

#916 Various small plugin scripting improvements
  Assets/Editor/LuaDocsGenerator.cs
  Assets/Resources/LuaModules/__autocomplete.lua
  Assets/Scripts/API/ApiManager.cs
  Assets/Scripts/API/ApiMethods.EditableModels.cs
  Assets/Scripts/API/ApiMethods.Utils.cs
  Assets/Scripts/API/ApiMethods.cs
  Assets/Scripts/API/Lua/LuaManager.cs
  Assets/Scripts/API/Lua/Wrappers/CameraPathListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/ColorApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/EnvironmentListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/GroupListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/GuideApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/GuideListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/ImageListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/LayerListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/MatrixApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/MatrixListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/ModelApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/ModelListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/OpenBrushApiWrapperUtils.cs
  Assets/Scripts/API/Lua/Wrappers/Path2dApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/PathApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/PathListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/RotationApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/SketchApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/StrokeApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/StrokeListApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/SymmetryApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/TransformApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/Vector2ApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/Vector3ApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/Vector4ApiWrapper.cs
  Assets/Scripts/API/Lua/Wrappers/VideoListApiWrapper.cs
  Assets/Scripts/PointerManager.cs
  Assets/Scripts/Widgets/GrabWidget.cs
  Assets/Scripts/Widgets/ImageWidget.cs
  Assets/Scripts/Widgets/ModelWidget.cs
  Assets/Scripts/Widgets/TextWidget.cs
  Assets/Scripts/Widgets/VideoWidget.cs
Labels: enhancement

#920 Fix API brush smoothing logic
  Assets/Scripts/API/ApiManager.cs
  Assets/Scripts/API/ApiMethods.DrawStrokes.cs
  Assets/Scripts/API/ApiMethods.cs
  Assets/Scripts/API/DrawStrokes.cs
Labels: bugfix
