Repository icosa-foundation/open-brush, pull requests merged in 2025-08, with the labels that each got.

#883 Partial fix for "Smoke" and WIP support for baking more than just vertex position
  Assets/Prefabs/BrushBaker.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Export/BrushBaker.cs
  Assets/Shaders/BrushBaker Compute/X/bakeDanceFloor.compute
  Assets/Shaders/BrushBaker Compute/bakeSmoke.compute
Labels: bugfix

#890 Add Mac (non-VR) releases to Itch
  .github/workflows/build.yml
Labels: infrastructure

#889 Fix various issues related to additive loading
  Assets/Editor/Tests/TestBrush.cs
  Assets/Scripts/InitNoHeadsetMode.cs
  Assets/Scripts/Save/SaveLoadScript.cs
  Assets/Scripts/Save/SketchWriter.cs
  Assets/Scripts/SceneScript.cs
  Assets/Scripts/SketchControlsScript.cs
Labels: bug
