Repository icosa-foundation/open-brush, pull requests merged in 2025-04, with the labels that each got.

#832 Zapbox fixes: tutorial, controller materials, and laser pointer
  Assets/Materials/TransformModeZapparController.mat
  Assets/Materials/TransformModeZapparController.mat.meta
  Assets/Models/Input/Zapbox.meta
  Assets/Models/Input/Zapbox/Materials.meta
  Assets/Models/Input/Zapbox/Materials/Zapbox_Controller_Colour.mat
  Assets/Models/Input/Zapbox/Materials/Zapbox_Controller_Colour.mat.meta
  Assets/Models/Input/Zapbox/Zapbox_Controller_Colour.png
  Assets/Models/Input/Zapbox/Zapbox_Controller_Colour.png.meta
  Assets/Models/Input/Zapbox/Zapbox_Controller_Left.fbx
  Assets/Models/Input/Zapbox/Zapbox_Controller_Left.fbx.meta
  Assets/Models/Input/Zapbox/Zapbox_Controller_Right.fbx
  Assets/Models/Input/Zapbox/Zapbox_Controller_Right.fbx.meta
  Assets/Prefabs/ControllerRightZapboxHighlightEffect.prefab
  Assets/Prefabs/ControllerRightZapboxHighlightEffect.prefab.meta
  Assets/Prefabs/VrSystems/ControllerGeometries/ZapboxLeftControllerGeometry.prefab
  Assets/Prefabs/VrSystems/ControllerGeometries/ZapboxRightControllerGeometry.prefab
  Assets/Prefabs/VrSystems/VrControllers/UnityXR/UnityXRZapboxControls.prefab
  Assets/Scripts/App.cs
  Assets/Scripts/MaterialCache.cs
  Assets/Scripts/Tutorials/HintObjectScript.cs
  Assets/Shaders/LaserPointerLine.shader
Labels: enhancement

#837 Fix Arbor XR release channel updates which use a version ID instead of a version (despite calling the parameter --version)
  .github/workflows/build.yml
Labels: infrastructure

#838 Use JSON format for abxr-cli
  .github/workflows/build.yml
Labels: infrastructure

#839 Faster cleanup step (saves about 1 minute in the slow case)
  .github/workflows/build.yml
Labels: infrastructure

#840 Revert accidental change to Unity splash screen setting
  ProjectSettings/ProjectSettings.asset
Labels: bugfix

#841 Add a github action to automatically comment if/when Packages or Project Settings are changed
  .github/workflows/highlight_manual_review_files.yml
Labels: infrastructure

#843 Fix missing line that caused duplicate comments
  .github/workflows/highlight_manual_review_files.yml
Labels: infrastructure

#842 Fix builds on forks; move defines from ProjectSettings to build.yml on a per-platform basis
  .github/workflows/build.yml
  Assets/Scripts/Multiplayer/MultiplayerDataStructs.cs
  Assets/Scripts/Multiplayer/MultiplayerManager.cs
  Assets/Scripts/Multiplayer/RemotePlayer.cs
  ProjectSettings/ProjectSettings.asset
  README.md
Labels: bugfix, infrastructure

#845 Silence warnings from setup-uv
  .github/workflows/build.yml
Labels: infrastructure

#846 Use literal newline to fix file listing in the warning comment
  .github/workflows/highlight_manual_review_files.yml
Labels: infrastructure

#847 Update pre-commit config
  .pre-commit-config.yaml
  Support/Python/unitybuild/utils.py
  Support/bin/animateTriangles.py
  Support/bin/tbdroid.py
Labels: infrastructure
